"use client";

import { FormEvent, useMemo, useState } from "react";
import Link from "next/link";

type Page = "dashboard" | "journey" | "assessment" | "tutor" | "progress" | "notebooks" | "skill";
type Status = "mastered" | "proficient" | "familiar" | "attempted" | "not-started" | "struggling";

type Skill = { name: string; short: string; status: Status; level: number; required: number; unit: number; next?: boolean; quiz?: boolean; test?: boolean };

const skills: Skill[] = [
  { name: "Spreadsheets", short: "Sheets", status: "mastered", level: 3, required: 3, unit: 1 },
  { name: "SQL fundamentals", short: "SQL", status: "proficient", level: 2, required: 3, unit: 1, next: true, quiz: true },
  { name: "Relational modeling", short: "Modeling", status: "familiar", level: 1, required: 2, unit: 1 },
  { name: "Descriptive statistics", short: "Stats", status: "proficient", level: 2, required: 3, unit: 2, quiz: true },
  { name: "Probability", short: "Probability", status: "attempted", level: 1, required: 2, unit: 2 },
  { name: "Basic Python", short: "Python", status: "attempted", level: 1, required: 3, unit: 3, next: true, quiz: true },
  { name: "pandas", short: "pandas", status: "not-started", level: 0, required: 3, unit: 3 },
  { name: "Data cleaning", short: "Cleaning", status: "not-started", level: 0, required: 3, unit: 4, quiz: true },
  { name: "Data visualization", short: "Visuals", status: "not-started", level: 0, required: 3, unit: 4 },
  { name: "Communicating results", short: "Storytelling", status: "not-started", level: 0, required: 2, unit: 5, test: true },
];

const statusStyle: Record<Status, string> = {
  mastered: "bg-violet-700 border-violet-700 text-white",
  proficient: "bg-violet-300 border-violet-300 text-violet-950",
  familiar: "bg-amber-500 border-amber-500 text-white",
  attempted: "bg-white border-amber-700 text-amber-800",
  "not-started": "bg-white border-slate-300 text-slate-500",
  struggling: "bg-rose-100 border-rose-500 text-rose-700",
};

const legend: Array<[Status, string]> = [["mastered", "Mastered"], ["proficient", "Proficient"], ["familiar", "Familiar"], ["attempted", "Attempted"], ["not-started", "Not started"]];

function Pips({ level, required }: { level: number; required: number }) {
  return <span className="inline-flex gap-1" aria-label={`Level ${level} of ${required} required`}>{[1, 2, 3, 4].map((n) => <i key={n} className={`h-1.5 w-4 rounded-full ${n <= level ? "bg-current" : "bg-current/20"}`} />)}</span>;
}

function SkillChip({ skill, onSelect }: { skill: Skill; onSelect: (skill: Skill) => void }) {
  return <button onClick={() => onSelect(skill)} className={`node-pop group relative flex h-[68px] w-[104px] flex-col justify-between rounded-xl border-2 p-2 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${statusStyle[skill.status]} ${skill.next ? "ring-4 ring-blue-200 ring-offset-2" : ""}`}>
    {skill.next && <span className="absolute -top-7 left-0 whitespace-nowrap text-[10px] font-black uppercase tracking-wide text-blue-700">Up next</span>}
    <span className="text-xs font-extrabold leading-tight">{skill.short}</span><Pips level={skill.level} required={skill.required} />
  </button>;
}

function SkillMap({ onSelect }: { onSelect: (skill: Skill) => void }) {
  return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-wider text-emerald-700">Your learning map</p><h2 className="mt-1 text-2xl font-black tracking-tight">Data Analyst foundations</h2><p className="mt-1 text-sm text-slate-600">10 skills · Your journey adjusts as you learn.</p></div><a className="rounded-xl border border-slate-300 px-3 py-2 text-sm font-bold text-slate-700 hover:bg-slate-50" href="/journey">View plan</a></div>
    <div className="mt-6 flex flex-wrap gap-x-4 gap-y-2 border-y border-slate-100 py-3">{legend.map(([key, label]) => <span key={key} className="flex items-center gap-2 text-xs font-semibold text-slate-600"><i className={`h-4 w-4 rounded border-2 ${statusStyle[key]}`} />{label}</span>)}<span className="flex items-center gap-1 text-xs text-slate-500">⚡ Quiz</span><span className="flex items-center gap-1 text-xs text-slate-500">★ Unit test</span></div>
    <div className="mt-2 divide-y divide-slate-100">{[1,2,3,4,5].map(unit => <div className="grid grid-cols-[80px_1fr] gap-3 py-5" key={unit}><div className="pt-2 text-sm font-black text-slate-700">Unit {unit}</div><div className="flex flex-wrap items-center gap-3">{skills.filter(x => x.unit === unit).map(x => <div key={x.name} className="flex items-center gap-2"><SkillChip skill={x} onSelect={onSelect}/>{x.quiz && <span title="Quiz" className="rounded-lg bg-slate-100 px-2 py-1 text-lg">⚡</span>}{x.test && <span title="Unit test" className="rounded-lg bg-slate-100 px-2 py-1 text-lg">★</span>}</div>)}{unit === 1 && <span className="text-sm text-slate-500">A strong base—keep your momentum.</span>}</div></div>)}</div>
    <div className="mt-6 rounded-2xl border border-blue-200 bg-blue-50 p-4"><p className="text-sm font-black uppercase tracking-wide text-blue-900">📖 Course challenge</p><p className="mt-1 text-sm text-blue-800">Test your knowledge across every skill once you are ready.</p><button className="mt-2 text-sm font-black text-blue-700 hover:underline">Preview course challenge →</button></div>
  </section>;
}

function Dashboard() {
  const [selected, setSelected] = useState<Skill>(skills[1]);
  return <div className="space-y-6"><section className="rounded-3xl bg-emerald-700 px-6 py-7 text-white sm:px-9"><p className="font-bold text-emerald-100">Tuesday, learning day</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black tracking-tight sm:text-4xl">Hi Alex, ready for your next win?</h1><p className="mt-2 text-emerald-100">You are building the skills for your Data Analyst goal.</p></div><div className="rounded-2xl bg-white/15 px-5 py-3 text-center"><b className="block text-2xl">4</b><span className="text-xs font-bold uppercase tracking-wide text-emerald-100">day streak 🔥</span></div></div></section>
  <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_300px]"><SkillMap onSelect={setSelected}/><aside className="space-y-5"><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-wider text-slate-500">This week</p><h2 className="mt-1 text-xl font-black">2 missions to go</h2><div className="mt-4 space-y-3"><Mission title="SQL: filter a dataset" time="25 min" done/><Mission title="Python practice: lists" time="30 min"/><Mission title="Stats: describe a distribution" time="20 min"/></div><Link href="/journey" className="mt-5 block text-center text-sm font-black text-emerald-700 hover:underline">Open weekly plan →</Link></section><section className="rounded-3xl border border-amber-200 bg-amber-50 p-5"><p className="text-sm font-black text-amber-900">Ready to verify?</p><p className="mt-1 text-sm text-amber-800">Your spreadsheet skill is self-reported. A short assessment can verify it.</p><Link href="/assessment/spreadsheets" className="mt-3 inline-block text-sm font-black text-amber-900 underline">Start assessment →</Link></section><section className="rounded-3xl border border-slate-200 bg-white p-5"><p className="text-xs font-black uppercase tracking-wider text-slate-500">Selected skill</p><h3 className="mt-1 text-xl font-black">{selected.name}</h3><div className="mt-2 flex items-center gap-2 text-sm text-slate-600"><Pips level={selected.level} required={selected.required}/><span>Level {selected.level} · Target {selected.required}</span></div><p className="mt-3 text-sm text-slate-600">{selected.status === "not-started" ? "This unlocks after its prerequisite mission is complete." : "Your next small step is already in this week’s plan."}</p><Link className="mt-3 inline-block text-sm font-black text-emerald-700 hover:underline" href="/skills/sql">Open skill details →</Link></section></aside></div></div>;
}

function Mission({ title, time, done }: { title: string; time: string; done?: boolean }) { return <div className="flex gap-3"><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full border-2 text-[10px] ${done ? "border-emerald-600 bg-emerald-600 text-white" : "border-slate-300"}`}>{done ? "✓" : ""}</span><div><p className={`text-sm font-bold ${done ? "text-slate-400 line-through" : "text-slate-800"}`}>{title}</p><p className="text-xs text-slate-500">{time}</p></div></div> }

function Journey() { return <div className="space-y-6"><section><p className="text-sm font-bold uppercase tracking-wider text-emerald-700">Your adaptive plan</p><h1 className="mt-1 text-3xl font-black">A small, focused week</h1><p className="mt-2 max-w-2xl text-slate-600">Designed around your 6 available hours and the skills that unlock the most progress.</p></section><div className="grid gap-5 md:grid-cols-4">{[1,2,3,4].map((week) => <section key={week} className={`rounded-3xl border p-5 ${week === 1 ? "border-emerald-300 bg-emerald-50" : "border-slate-200 bg-white"}`}><p className="text-xs font-black uppercase tracking-widest text-slate-500">Week {week}{week === 1 && " · Now"}</p><h2 className="mt-2 text-lg font-black">{["SQL foundations", "Python basics", "Working with data", "Tell the story"][week-1]}</h2><div className="mt-5 space-y-4">{["Learn", "Practice", "Reflect"].map((kind,index)=><div key={kind} className="border-l-2 border-emerald-500 pl-3"><p className="text-sm font-bold">{kind}: {index === 0 ? "Curated lesson" : index === 1 ? "Hands-on mission" : "Quick check-in"}</p><p className="text-xs text-slate-500">{20 + index * 15} min</p></div>)}</div></section>)}</div><section className="rounded-3xl border border-blue-200 bg-blue-50 p-6"><p className="font-black text-blue-900">Your plan can change—and that is a feature.</p><p className="mt-1 text-sm text-blue-800">Assessment results, completed missions, and missed work make the next plan more useful. You will always see what changed and why.</p></section></div> }

function Assessment() { const [step,setStep]=useState(0); const [done,setDone]=useState(false); const prompts=["Which SQL clause filters rows before grouping?","Write one sentence explaining when you would use a LEFT JOIN.","A table has duplicate customer IDs. What is your first check?"]; return <div className="mx-auto max-w-2xl"><p className="text-sm font-bold uppercase tracking-wider text-emerald-700">SQL verification</p><h1 className="mt-1 text-3xl font-black">Show what you know</h1>{done?<section className="mt-6 rounded-3xl border border-emerald-200 bg-emerald-50 p-7"><span className="text-4xl">✦</span><h2 className="mt-3 text-2xl font-black text-emerald-950">Assessment complete</h2><p className="mt-2 text-emerald-900">Your results will verify your current level and may refine your plan.</p><div className="mt-5 rounded-2xl bg-white p-4"><p className="text-sm font-bold">What happens next?</p><p className="mt-1 text-sm text-slate-600">Review feedback, then see any updates to your learning map.</p></div><a className="mt-5 inline-block rounded-xl bg-emerald-700 px-4 py-3 font-black text-white" href="/dashboard">See your learning map →</a></section>:<section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between text-sm font-bold text-slate-500"><span>Question {step+1} of {prompts.length}</span><span>{Math.round(((step+1)/prompts.length)*100)}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-600" style={{width:`${((step+1)/prompts.length)*100}%`}}/></div><h2 className="mt-8 text-xl font-black">{prompts[step]}</h2>{step===0?<div className="mt-5 space-y-3">{["WHERE","ORDER BY","HAVING","SELECT"].map(x=><label key={x} className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-4 font-semibold hover:border-emerald-400"><input name="choice" type="radio"/><span>{x}</span></label>)}</div>:<textarea className="mt-5 min-h-36 w-full rounded-xl border border-slate-300 p-4 outline-none focus:border-emerald-600" placeholder="Write your answer here..."/>}<button onClick={()=>step===prompts.length-1?setDone(true):setStep(step+1)} className="mt-6 rounded-xl bg-emerald-700 px-5 py-3 font-black text-white hover:bg-emerald-800">{step===prompts.length-1?"Submit answers":"Continue"} →</button></section>}</div> }

function Tutor() { const [messages,setMessages]=useState([{from:"tutor",text:"Hi Alex! I’m here to help you make sense of your learning map. What would you like to work through?"}]); const [value,setValue]=useState(""); function submit(e:FormEvent){e.preventDefault();if(!value.trim())return;setMessages(m=>[...m,{from:"you",text:value},{from:"tutor",text:"A good next step is your SQL filtering mission. It is short, practical, and supports the data-cleaning unit that comes next. Want a hint before you begin?"}]);setValue("")} return <div className="mx-auto flex min-h-[620px] max-w-3xl flex-col rounded-3xl border border-slate-200 bg-white shadow-sm"><header className="flex items-center gap-3 border-b border-slate-100 p-5"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-emerald-100 text-xl">✦</span><div><h1 className="font-black">Your learning tutor</h1><p className="text-sm text-emerald-700">Friendly · Detailed · Uses analogies</p></div></header><main className="flex-1 space-y-4 p-5">{messages.map((m,i)=><div key={i} className={`max-w-[80%] rounded-2xl px-4 py-3 text-sm leading-relaxed ${m.from==="you"?"ml-auto bg-emerald-700 text-white":"bg-slate-100 text-slate-800"}`}>{m.text}</div>)}<div className="flex flex-wrap gap-2"><button onClick={()=>setValue("What should I do this week?")} className="rounded-full border border-slate-300 px-3 py-2 text-xs font-bold hover:bg-slate-50">What should I do this week?</button><button onClick={()=>setValue("Why is SQL important for my goal?")} className="rounded-full border border-slate-300 px-3 py-2 text-xs font-bold hover:bg-slate-50">Why SQL first?</button></div></main><form onSubmit={submit} className="flex gap-3 border-t border-slate-100 p-4"><input value={value} onChange={e=>setValue(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-emerald-600" placeholder="Ask about your plan or a concept..."/><button className="rounded-xl bg-emerald-700 px-5 font-black text-white">Send</button></form></div> }

function Progress() { const blocks=[["✓","Acquired","Spreadsheets","border-emerald-200 bg-emerald-100 text-emerald-700"],["↗","In progress","SQL · 62%","border-blue-200 bg-blue-100 text-blue-700"],["!","Remaining gaps","Python, pandas, cleaning","border-amber-200 bg-amber-100 text-amber-700"],["→","Next best step","Finish your SQL mission","border-violet-200 bg-violet-100 text-violet-700"]]; return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-wider text-emerald-700">Your progress</p><h1 className="mt-1 text-3xl font-black">A clearer picture of your growth</h1></div><button className="rounded-xl bg-emerald-700 px-4 py-3 font-black text-white">Generate fresh report</button></div><section className="rounded-3xl bg-violet-700 p-7 text-white"><p className="text-violet-200 font-bold">Your report says</p><h2 className="mt-2 max-w-2xl text-2xl font-black">You have a strong starting point. Build SQL confidence next, then use Python to make your analysis repeatable.</h2></section><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{blocks.map(([icon,title,content,colors])=><section key={title} className={`rounded-3xl border bg-white p-5 shadow-sm ${colors.split(" ")[0]}`}><span className={`grid h-9 w-9 place-items-center rounded-xl font-black ${colors.split(" ").slice(1).join(" ")}`}>{icon}</span><h2 className="mt-4 text-lg font-black">{title}</h2><p className="mt-2 text-sm text-slate-600">{content}</p></section>)}</div><section className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-black">Your next steps</h2><ol className="mt-4 space-y-3">{["Complete the SQL filtering practice","Verify your spreadsheets level","Start the Python foundations unit"].map((x,i)=><li className="flex gap-3" key={x}><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-emerald-100 text-xs font-black text-emerald-800">{i+1}</span><span className="font-semibold text-slate-700">{x}</span></li>)}</ol></section></div> }

function Notebooks(){ const [notes,setNotes]=useState(["SQL joins cheat sheet","Charts that tell a story"]); const [creating,setCreating]=useState(false); const [title,setTitle]=useState(""); return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-wider text-emerald-700">Study notebooks</p><h1 className="mt-1 text-3xl font-black">Keep your useful ideas close</h1><p className="mt-2 text-slate-600">Link notes to skills so your tutor can use them as context.</p></div><button onClick={()=>setCreating(true)} className="rounded-xl bg-emerald-700 px-4 py-3 font-black text-white">+ New notebook</button></div>{creating&&<form onSubmit={e=>{e.preventDefault();if(title.trim()){setNotes(x=>[...x,title]);setTitle("");setCreating(false)}}} className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><label className="block text-sm font-bold">Notebook title<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3" placeholder="e.g. My Python patterns"/></label><div className="mt-3 flex gap-3"><button className="rounded-lg bg-emerald-700 px-3 py-2 text-sm font-black text-white">Create notebook</button><button type="button" onClick={()=>setCreating(false)} className="text-sm font-bold text-slate-600">Cancel</button></div></form>}<div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{notes.map((note,i)=><section key={note} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><span className="text-3xl">📓</span><h2 className="mt-4 text-lg font-black">{note}</h2><p className="mt-2 text-sm text-slate-500">Linked to {i===0?"SQL fundamentals":"Data visualization"}</p><p className="mt-4 text-sm text-slate-600">Capture explanations, examples, and questions for your future self.</p><button className="mt-5 text-sm font-black text-emerald-700 hover:underline">Open notebook →</button></section>)}</div></div> }

function SkillDetail(){ return <div className="mx-auto max-w-3xl"><Link href="/dashboard" className="text-sm font-bold text-emerald-700">← Back to learning map</Link><section className="mt-5 rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-wider text-violet-700">Unit 1 · Data foundations</p><h1 className="mt-1 text-3xl font-black">SQL fundamentals</h1><p className="mt-2 text-slate-600">Ask useful questions of data with confidence.</p></div><span className="rounded-full bg-violet-100 px-3 py-2 text-sm font-black text-violet-800">Self-reported</span></div><div className="mt-7 grid gap-5 sm:grid-cols-3"><div><p className="text-xs font-black uppercase text-slate-500">Current level</p><p className="mt-1 text-2xl font-black">2</p></div><div><p className="text-xs font-black uppercase text-slate-500">Target level</p><p className="mt-1 text-2xl font-black">3</p></div><div><p className="text-xs font-black uppercase text-slate-500">Progress</p><p className="mt-1 text-2xl font-black">62%</p></div></div><div className="mt-7 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[62%] rounded-full bg-emerald-600"/></div><h2 className="mt-8 text-xl font-black">Your next mission</h2><div className="mt-3 rounded-2xl bg-slate-50 p-4"><p className="font-bold">Filter a customer dataset</p><p className="mt-1 text-sm text-slate-600">Write a query that selects active customers in a given region.</p><button className="mt-3 text-sm font-black text-emerald-700">Start mission →</button></div><Link href="/assessment/sql" className="mt-5 inline-block rounded-xl border-2 border-emerald-700 px-4 py-3 font-black text-emerald-700 hover:bg-emerald-50">Verify this skill</Link></section></div> }

export function LearningExperience({ page }: { page: Page }) { const body=useMemo(()=>({dashboard:<Dashboard/>,journey:<Journey/>,assessment:<Assessment/>,tutor:<Tutor/>,progress:<Progress/>,notebooks:<Notebooks/>,skill:<SkillDetail/>})[page],[page]); return <>{body}{page!=="tutor"&&<a href="/tutor" aria-label="Open tutor" className="fixed bottom-6 right-6 grid h-14 w-14 place-items-center rounded-full bg-emerald-700 text-xl text-white shadow-lg transition hover:scale-105">✦</a>}</> }
